# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 727a4f72e42a1d8d7770abdb44329f3946dedeb2f6b7f61a4b0541fd1de6948a51bef62fc4bc3970e4601e76db172165072e9be4330a3397ae9caea4a4c533b9

test:
  secret_key_base: 929244260d0095caaab5cfb98ea70777eb5f00a1cd66a3f57e26e9981a75309513d84b14d65052594e7cdbff49e21e1421d25f8564c212ca50bcab2d817eff67

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
